#!/bin/bash

# A credential helper for git to retrieve usernames and passwords from pass.
# For general usage, see https://git-scm.com/docs/gitcredentials.
# Here's a quick version:
# 1. Put this somewhere in your path.
# 2. git config --global credential.helper pass

declare -A attrib
command -v pass >/dev/null 2>&1 || exit

if [[ $1 = "get" ]]; then
	read line
	while [[ -n "$line" ]]; do
	    echo "Read stdin: $line" >/dev/stderr
		key=${line%%=*}
		value=${line#*=}
		if [[ $key = "path" ]]; then
            attrib[$key]=${value%.git}
        else
            attrib[$key]=$value
        fi
		read line
	done

	if [[ ${attrib['protocol']} != "https" ]]; then
		exit
	fi

	if [ -z "${attrib["host"]}" ]; then
		exit
	fi

    echo "Looking for '${attrib[username]}@${attrib[host]}/${attrib[path]}'" >/dev/stderr
    pass=$(pass show "${attrib[username]}@${attrib[host]}/${attrib[path]}")

	if [[ -z "$pass" ]]; then
		echo "Couldn't find host in pass storage." >/dev/stderr
		exit
	fi

	echo username="${attrib["username"]}"
	echo password="$pass"
fi
