#!/bin/bash

# A credential helper for git to retrieve usernames and passwords from pass.
# For general usage, see https://git-scm.com/docs/gitcredentials.
# Here's a quick version:
# 1. Put this somewhere in your path.
# 2. git config --global credential.helper pass

declare -A attrib
if ! command -v pass >/dev/null 2>&1; then
    echo "Couldn't find command pass" >&2
    exit
fi

if [[ $1 = get ]]; then
    read line
    while [[ -n "$line" ]]; do
        key=${line%%=*}
        value=${line#*=}
        if [[ $key = "path" ]]; then
            attrib[$key]=${value%.git}
        else
            attrib[$key]=$value
        fi
        read line
    done

    if [[ ${attrib[protocol]} != "https" ]]; then
        exit
    fi

    if [[ -z "${attrib[host]}" ]]; then
        exit
    fi

    if [[ -z "${attrib[username]}" ]]; then
        attrib[username]=$(id -nu)
    fi

    for key in "${attrib[username]}@${attrib[host]}/${attrib[path]}" \
               "${attrib[username]}@${attrib[host]}" \
               "${attrib[host]}/${attrib[path]}" \
               "${attrib[host]}"; do
        pass=$(pass show "$key" 2>/dev/null)

        if [[ -n "$pass" ]]; then
            break
        fi
    done

    if [[ -z "$pass" ]]; then
        echo "Couldn't find host in pass storage." >&2
        exit
    fi

    echo username="${attrib["username"]}"
    echo password="$pass"
fi
